### ISSUE TITLE
Unable to transmit string correctly

### ISSUE THREAD

**Issue by ghost** [PowerBroker2/SerialTransfer#11]
**Describe the bug**
I tested with nodemcu and due , examples work fine 
So I tried to transfer the string , 

**To Reproduce**
1. Download [them](https://cdn.discordapp.com/attachments/627701490173345811/660058877852909578/code.rar) and upload to arduino
2. See error ' ? '

**Expected behavior**
rx should show the string , but I get a bunch of  ' ? '

**Screenshots**
![unknown (5)](https://user-images.githubusercontent.com/24543050/71512968-696a3500-28d3-11ea-9d10-d658b0cd87ff.png)

 - Board: NodeMCU and Arduino due
 - Arduino IDE [1.8.10]

**Comment by PowerBroker2** [comment]
Using "S"trings isn't the best idea to use with Arduinos because they can lead to memory issues and whatnot.

Regardless, I'll take a look

**Comment by PowerBroker2** [comment]
I've decided that the use of Strings within structs will not be supported because of how Strings work and are stored in memory. As a fix, you can change your struct members from Strings to char arrays and use the str.c_str() member function to convert your strings. See this link: [http://www.cplusplus.com/reference/string/string/c_str/](url)

**Comment by PowerBroker2** [comment]
I may soon add a new function to transfer individual Strings - just not within structs.

**Comment by ghost** [comment]
I tried to transmit using char array, but I couldn't receive it 
[code.zip](https://github.com/PowerBroker2/SerialTransfer/files/4006830/code.zip)
![unknown (6)](https://user-images.githubusercontent.com/24543050/71540529-cc68d400-2986-11ea-9c91-7b04efd55ec9.png)

**Comment by PowerBroker2** [comment]
Your code won't compile - not even sure how you were able to test it...
Error:

> error: flexible array member

You will need to specify a max array length for the member char arrays. I tested your code specifying max array length of 10 for each and got successful results.

Here's what I changed the struct definition to (in both RX and TX sketches):
```
struct STRUCT {
  char room_text[10];
  char user_text[10];
  char status_text[10];
} testStruct;
```

**Comment by ghost** [comment]
Thank you !
