### ISSUE TITLE
SerialTransfer <variable> breaks ability to read SD card.

### ISSUE THREAD

**Issue by SSolheim2000** [PowerBroker2/SerialTransfer#12]
Here's my code: [LED_Sequencer_Working_Copy - Copy.txt](https://github.com/PowerBroker2/SerialTransfer/files/4302865/LED_Sequencer_Working_Copy.-.Copy.txt)

**Describe the bug**
When I activate (uncomment) the line "SerialTransfer myTransfer;", my program can no longer read the DATA.txt file located on the SD card.

**To Reproduce**
1. I've added in the code from the "tx_simple" under the examples folder. (BTW, I've tested the tx_simple/rx_simple on their own and they work perfectly).
2. I'm using this example for the SD card shield's pinouts: https://www.mschoeffler.de/2017/02/22/how-to-use-the-microsd-card-adapter-with-the-arduino-uno/
3. With all of the added code from example file commented out, the program runs fine.
4. Uncommenting the "#include "SerialTransfer.h"" and it still runs fine.
5. Uncommenting the  "SerialTransfer myTransfer;" line and my code can no longer read the Data.txt file on my SD card.

**Expected behavior**
For SerialTransfer.h to be used in conjunction with my SD card reader.

**Screenshots**

**Desktop (please complete the following information):**
 - OS: Win 10

**Smartphone (please complete the following information):**
N/A

**Additional context**

**Comment by PowerBroker2** [comment]
> Uncommenting the "SerialTransfer myTransfer;" line and my code can no longer read the Data.txt file on my SD card.

What exactly do you mean? How do you know it's not reading the file?

**Comment by PowerBroker2** [comment]
Also, what Arduino are you using?

**Comment by SSolheim2000** [comment]
I'm using an UNO R3.
When I have the line not commented out, I get an error message in the Serial Monitor:

![Serial Monitor Error](https://user-images.githubusercontent.com/61861784/76157482-e2092100-60ce-11ea-9666-ebbe815a6982.jpg)

  // Setup for the Serial Transfer module
    #include <SerialTransfer.h>
    SerialTransfer myTransfer;

**Comment by SSolheim2000** [comment]
When it's commented out, I get the expected data in the Serial Monitor:
![Serial Monitor Normal](https://user-images.githubusercontent.com/61861784/76157500-3ad8b980-60cf-11ea-91c4-e8a29affe8f8.jpg)


// Setup for the Serial Transfer module
    #include <SerialTransfer.h>
    //SerialTransfer myTransfer;

**Comment by PowerBroker2** [comment]
There's really no reason the library is causing an issue. I've been able to use the library successfully with an SD card [(see here)](https://github.com/PowerBroker2/RND_Flight_Code/blob/master/Data_Logger/Data_Logger.ino).

The only thing I can think of is that you're using ~73% of the Uno's dynamic memory. Even then, I'd only get worried once it hits 90%, so idk.

I suggest getting something like a Mega or (better still) a Teensy 3.5/3.6. They have more memory and hardware serial ports and the Teensy specifically has a ton more processing power.

**Comment by SSolheim2000** [comment]
I changed all my "int" variables to "byte" and now it's working fine. Thanks for the good lead and quick responses!!
