### ISSUE TITLE
Add support for acessing packet ID

### ISSUE THREAD

**Issue by finostro** [PowerBroker2/SerialTransfer#22]
**Is your feature request related to a problem? Please describe.**
I am sending multiple message types, And would like to fill different objects depending on the packetID, Buy IdByte is private. 

**Describe the solution you'd like**
make idByte public or make an access function to it

**Describe alternatives you've considered**
For now I will use message length to differentiate the messages, but using the packet ID seems like a better option.

**Comment by PowerBroker2** [comment]
Should be fixed in [release 2.0.2](https://github.com/PowerBroker2/SerialTransfer/releases/tag/2.0.2)

**Comment by finostro** [comment]
Great! Thank you!
