### ISSUE TITLE
Arduino to Arduino bidirectional communication over Bluetooth modules

### ISSUE THREAD

**Issue by kayyumuddin** [PowerBroker2/SerialTransfer#40]

**Comment by PowerBroker2** [comment]
I'm not sure I understand the problem, can you explain your issue? You can use this library with ESP32 modules to include the ESP32 built-in serial bluetooth already. Are you asking for an additional example or an actual new library function? Did you try to communicate between two ESP32s over bluetooth with the lib?

You shouldn't need a lib like this if you're using WiFi.

**Comment by kayyumuddin** [comment]
Additional example,you didn't mention any serial bluetooth in Readme.md. I'm not familiar with Bluetooth module

**Comment by PowerBroker2** [comment]
That comes down to being familiar with your ESP32 - check out [this](https://randomnerdtutorials.com/esp32-bluetooth-classic-arduino-ide/). You can integrate it with the SerialTransfer library by passing a `BluetoothSerial` class instance into `SerialTransfer.begin()` like you would any other `Serial` or `SoftwareSerial` class instance
