### ISSUE TITLE
Trouble using SoftwareSeriel RS485

### ISSUE THREAD

**Issue by dk12651** [PowerBroker2/SerialTransfer#41]
**Describe the bug**
Not working with SoftwareSerial being used with RS485 shield http://store.linksprite.com/rs485-shield-for-arduino-v2-1/

using normal SoftwareSerial like:
`myRS485Serial.print(dataByte); `
works fine

```C++
struct STRUCT {
byte dataByte;
}data;

myTransfer.txObj(data, sizeof(data));
myTransfer.sendData(sizeof(data));
```

doesn't work. getting CRC_ERROR message at RX end

**Expected behavior**
byte dataByte should be assigned value at RX end

**Screenshots**

**Desktop (please complete the following information):**
 - OS: Win10
-IDE: Arduino 1.8.5
**Additional context**
When using the regular SoftwareSerial code, RS485Serial.**print**(dataByte); works as expected but RS485Serial.**write**(dataByte); does not. Looking through this libraries code, I noticed it had port->write in SerialTransfer.cpp. Could this be causing the problem? I have tried both installing library through library manager in IDE and installing folder from Github.

**Comment by PowerBroker2** [comment]
1. What is your library version? Note that the API changed with some of the latest versions where you can do the following:
```C++
struct STRUCT {
byte dataByte;
}data;

myTransfer.sendData(myTransfer.txObj(data));
```
or
```C++
struct STRUCT {
byte dataByte;
}data;

myTransfer.sendDatum(data);
```
2. Please post your entire TX and RX code

**Comment by dk12651** [comment]
I think I have figured out what the issue is.  Issue #20 was similar to the issue I was having.  
this does not work in my case. @PowerBroker2  wrote:
`myTransfer.rxObj(data, sizeof(data));`
another had:
`myTransfer.rxObj(data, sizeof(data),recSize);`
To make it work for me I have:
` myTransfer.rxObj(data, 0, sizeof(data));`
or 
`myTransfer.sendData(myTransfer.txObj(data));`

Full working code below

**TX**
`#include <SoftwareSerial.h>
#include "SerialTransfer.h"

SoftwareSerial RS485Serial(2, 7); // RX, TX

SerialTransfer myTransfer;//create SerialTransfer instance

struct STRUCT {
  int count0 = 0;
  int count1 = 1;
} data;

void setup() {
  Serial.begin(115200); // Initialize serial communications with the PC
  RS485Serial.begin(9600);
  myTransfer.begin(RS485Serial);
}

void loop() {
  myTransfer.sendDatum(data);
  Serial.print(data.count0);
  Serial.println(data.count1);
  data.count0++;
  data.count1++;
  delay(1000);
}`

**RX**
`#include <SoftwareSerial.h>
#include "SerialTransfer.h"

SoftwareSerial RS485Serial(2, 7); // RX, TX

SerialTransfer myTransfer;//create SerialTransfer instance

struct STRUCT {
  int count0;
  int count1;
} data;

void setup(){
  Serial.begin(115200);
  RS485Serial.begin(9600);
  myTransfer.begin(RS485Serial);
}

void loop(){
  if (myTransfer.available())
  {
    myTransfer.rxObj(data, 0, sizeof(data));
    Serial.print("Counter 0 = ");
    Serial.println(data.count0);
    Serial.print("Counter 1 = ");
    Serial.println(data.count1);
  }
  else if (myTransfer.status < 0){
    Serial.print("ERROR: ");
    if (myTransfer.status == -1)
      Serial.println(F("CRC_ERROR"));
    else if (myTransfer.status == -2)
      Serial.println(F("PAYLOAD_ERROR"));
    else if (myTransfer.status == -3)
      Serial.println(F("STOP_BYTE_ERROR"));
  }
}`
