### ISSUE TITLE
Library work with Arduino UNO and ESP32

### ISSUE THREAD

**Issue by blokerun** [PowerBroker2/SerialTransfer#46]
I cannot transfer different types of data between Arduino Uno and ESP32. If the data is of only one type, for example "float", then everything works, but if I use different types in the structure, for example "float" and "char", then the data on the receiving side (ESP32) is distorted. How to make the library work with different controllers?

**Comment by PowerBroker2** [comment]
Both boards are little-endian, so there shouldn't be a problem there (especially if sending just a float works). As for sending multiple values, it should work just fine and the problem is likely in the sketch. Can you post your code?

**Comment by blokerun** [comment]
There are no problems with identical boards. But I need to transfer data from Arduino UNO to ESP32.
I determined that if the  structure is formed like this:
```C++
struct STRUCT {
  byte arr[8];    // 8 bytes
  int32_t z;       // 4 bytes
  float y;          // 4 bytes
  int8_t alarm; //  variable size  1 byte, sketch don`t work
} ;
```
then the data on the receiving side is distorted! But if the variables in the structure are arranged like this:

```C++
struct STRUCT {
  byte arr[8];       // 8 bytes
  int32_t z;          // 4 bytes
  float y;             // 4 bytes
  int8_t alarm1;  // 1 byte, four the same variables   int8_t (total size of variables is 4 bytes) - sketch works good!
  int8_t alarm2;  // 1 byte
  int8_t alarm3;  // 1 byte
  int8_t alarm4;  // 1 byte
  
} ;
```
or, for example, like this:

```C++
struct STRUCT {
  byte arr[8];            // 8 bytes
  int32_t z;               // 4 bytes
  float y;                  // 4 bytes
  int16_t alarm1;    // 2 bytes  two the same variables   int16_t  (total size of variables is 4 bytes) - sketch works good!
  int16_t alarm2;    // 2 bytes
  
} ;
```
then on the receiving side everything works fine even on different platforms - Arduino UNO and ESP32

It turns out that the variables in the structure must somehow be "aligned" in multiples of 4 bytes? I cannot formulate it correctly. What do you advise? Thank you in advance!!!

**Comment by PowerBroker2** [comment]
Can you post your whole code - both sides?

**Comment by blokerun** [comment]
I've simplified my code to make it clearer. If there is a boolean variable in the structure - the data at the reception is distorted, if I remove the boolean variable - the code works fine. Вut if I put 4 boolean variables in the structure (like this: boolean flag1; boolean flag2; boolean flag3; boolean flag4;), everything works fine at the reception too! In general, between different controllers, the library works only if the type of variables in the structure has a size of 4 bytes or several identical variables together have a size multiple of 4. Do you understand what I want to say?
```C++
// This code for Arduino UNO
#include "SerialTransfer.h"

SerialTransfer myTransfer;


struct STRUCT {
 
  int32_t z;
  float y;
  boolean flag1;//       without a boolean variable works, with this variable - no

} ;

STRUCT testStruct;

void setup()
{
  Serial.begin(115200);
  myTransfer.begin(Serial);
  
  testStruct.z = 10;
  testStruct.y = 0.2;
  testStruct.flag1 = false;
  
  
}


void loop()
{
  // use this variable to keep track of how many
  // bytes we're stuffing in the transmit buffer
  uint16_t sendSize = 0;

  ///////////////////////////////////////// Stuff buffer with struct
  sendSize = myTransfer.txObj(testStruct, sendSize);


  ///////////////////////////////////////// Send buffer
  myTransfer.sendData(sendSize);
  delay(500);
}
```

```C++
// This code for ESP32
#include "SerialTransfer.h"

SerialTransfer myTransfer;


struct STRUCT {
 
  int32_t z;
  float y;
  boolean flag1; //       without a boolean variable works, with this variable - no

} ;

STRUCT testStruct;


void setup()
{
  Serial.begin(115200);
  Serial2.begin(115200);
  myTransfer.begin(Serial2);
}


void loop()
{
  if(myTransfer.available())
  {
    // use this variable to keep track of how many
    // bytes we've processed from the receive buffer
    uint16_t recSize = 0;

    recSize = myTransfer.rxObj(testStruct, recSize);
	
    Serial.print(testStruct.z);
    Serial.print("_");
    Serial.print(testStruct.y);
    Serial.print("_");
    Serial.print(testStruct.flag1);
    Serial.print(" | ");

   
    Serial.println();

 
  }
}
```

**Comment by akira-kun** [comment]
Does serialtransfer Uart, i2c ans SPI works with esp8266?

**Comment by PowerBroker2** [comment]
It works with UART and I2C, but I don't think it's supported for SPI

**Comment by akira-kun** [comment]
Very nice, and which one is faster and realible? I2c or serial uart? I need transfer large mp3 files downloaded from https

**Comment by PowerBroker2** [comment]
Max clock rate for most arduino boards is 400KHz, but UART maxes out at a baud of 2 million, so UART would be faster. You should do a little research and see if the ESP8266 can do I2C at over 2MHz - that would be the deciding factor.

**Comment by akira-kun** [comment]
I2C communication between two esp8266 could not be done, I've been trying to use wire.begin in many ports for SDA, SCL, but no way to make it go. Do you know what could be? Now Serial runs like a charm.

**Comment by PowerBroker2** [comment]
@blokerun 

My apologies for getting back to you so late, but I think I found the solution to your issue: When specifying your struct, use the "packed" attribute to make sure the struct is compatible across Arduinos. Here is how you would do it:

```C++
struct __attribute__((__packed__)) STRUCT {
  int32_t z;
  float y;
  boolean flag1; //       without a boolean variable works, with this variable - no
} ;
```

**See [here](https://gcc.gnu.org/onlinedocs/gcc-4.0.2/gcc/Type-Attributes.html) for more info**
