### ISSUE TITLE
'Serial1' was not declared in this scope

### ISSUE THREAD

**Issue by betyar** [PowerBroker2/SerialTransfer#48]
Hi,

I have been unable to compile my code because I keep receiving the following error:

`'Serial1' was not declared in this scope`

And yet everywhere I see examples without Serial1 not being declared so I can't understand why this is happening.

My code is as follows:

```C++
#include "SerialTransfer.h"

SerialTransfer myTransfer;

void setup()
{
  Serial.begin(115200);
  Serial1.begin(115200);
  myTransfer.begin(Serial1);
}

void loop()
{
  char buff[] = "hi";

  myTransfer.txObj(buff, sizeof(buff));
  myTransfer.sendData(sizeof(buff));
  delay(100);
}

```

Any ideas?

Thanks in advance.

**Comment by PowerBroker2** [comment]
Because you are using an Arduino that doesn't have multiple UART ports. Instead of using `Serial1`, you can use a [software serial port](https://www.arduino.cc/en/Reference/softwareSerial)
