### ISSUE TITLE
How do we specify which "node" an I2C packet gets sent to?

### ISSUE THREAD

**Issue by chrisco484** [PowerBroker2/SerialTransfer#51]
With serial there is only one other node - the one at the end of the serial link.

However with I2C working in a "multi master" environment, any node can send to any other node. 

How does the I2CTransfer get told the address of the node to send a frame to?

**Comment by PowerBroker2** [comment]
> With serial there is only one other node - the one at the end of the serial link.

That's not necessarily true, you can have multiple devices listening on the TX line of a UART port.

If you take a look at `sendData()` for I2C, the last parameter `targetAddress` allows you to choose what I2C slave will receive the packet. See below:

https://github.com/PowerBroker2/SerialTransfer/blob/950e7520028557a2f3b6af00f2b2ad85a7f8ffa3/src/I2CTransfer.cpp#L47-L76

**Comment by chrisco484** [comment]
> If you take a look at `sendData()` for I2C, the last parameter `targetAddress` allows you to choose what I2C slave will receive the packet. See below:

Doh! I must have missed that. That's awesome, thanks!
