### ISSUE TITLE
Resend when any transfer error

### ISSUE THREAD

**Issue by luc-github** [PowerBroker2/SerialTransfer#52]
Hi thank you for your work 😄 ,
 
I do not know if it is a feature request or documentation request

I see there are callback and error status  (CRC_ERROR/PAYLOAD_ERROR/STOP_BYTE_ERROR) but I do not understand if there is a way to ask for resend specific packet if any error happen. and eventually cancel transfer if error is not recoverable

Is this feature missing or I miss read the sources/examples ?

Thank you

**Comment by PowerBroker2** [comment]
There isn't a way to automatically request a packet resend. If you need a resend, you'll have to figure out what the best way to request a packet resend for your specific project. It could be as simple as a digital IO signal or as complicated as sending a specific packet to the original sender to trigger a resend.

**Comment by luc-github** [comment]
yes my guessing was it need to be handle using callback - right ?
but I do not see how the callback get the status error

**Comment by PowerBroker2** [comment]
You don't need to use callbacks, but if you do use callbacks, you can still access the status member of the SerialTransfer class like this:

```C++
void someCallback()
{
  if (myTransfer.status <= 0)
  {
    // trigger resend
  }
}
```

Note the possible values of `status` is as follows:
https://github.com/PowerBroker2/SerialTransfer/blob/950e7520028557a2f3b6af00f2b2ad85a7f8ffa3/src/Packet.h#L22-L27

**Comment by luc-github** [comment]
excellent thank you ^_^
