### ISSUE TITLE
Make Arduino talk to Pi Pico (MicroPhyton poort?)

### ISSUE THREAD

**Issue by Superkris83** [PowerBroker2/SerialTransfer#56]
Hi! I have been using this library for a project where I share a number of variables between 2 Arduinos. 

I'm thinking about changing one of the Arduino's to a Raspberry Pi Pico. The physical layer is handled by MAX488 chips in RS422.

Would it be possible to get this library working on the Pi Pico? I see you made a Phyton version, but i guess its not the same as the MicroPhython on the Pi Pico.

Also, would there be any issues with these 2 MCU's talking to eachother? I guess as long as the baudrate is the same and the strukt is the same, it should work.  I need to transfer mostly floats, unsigned longs, intergers, and booleans. 

And again, thank you so much for this great library!

**Comment by PowerBroker2** [comment]
If you use [this pySerial lib](https://github.com/pfalcon/pycopy-serial), pySerialTransfer might be able to work. Be aware of potential installation issues like [this one](https://forum.micropython.org/viewtopic.php?t=285).

Actually, you're going to need to do something similar (replace big boy Python packages used WITHIN pySerialTransfer with microPython versions) with `os`, `json`, etc.

If you get it to work in microPython, I would love to know how. I could add it to the documentation for others interested in doing just that.
