### ISSUE TITLE
Start / End Markers

### ISSUE THREAD

**Issue by Eddiiie** [PowerBroker2/SerialTransfer#6]
Hello,

I am considering using your library for a device I am hacking on as your packet format matches the device's packet almost exactly.  

On my device start is 0xAA and end is 0x55 ..    Your's are different and I can change that but in both implementations there is a possibility of the checksum total could be a value in the stream / packet.

In my situation, then end Char is 0x55, a capital U.   There is a real possibility (although small) that U can be part of the message and not the end of message.

Does your library account for this situation or event?

Off to learn about COBS now.  

Thank you!!

**Comment by PowerBroker2** [comment]
With my library, you can have a payload byte that is equal to the end marker (mine being 0x81) and it will parse perfectly fine. The available() function doesn't check for the reception of the end marker while parsing the payload. It's only after it matches checksums does it see if the next received byte is the end marker.

Does this answer your question?

I'm certain that this library will work for your application!
