### ISSUE TITLE
library makes i2c lcd flash

### ISSUE THREAD

**Issue by emmanuelsheshi** [PowerBroker2/SerialTransfer#63]
good day sir, thanks so much for the library. but i noticed that it makes my i2c lcd flash. what can i do to resolve this? thanks in advance...

**Comment by PowerBroker2** [comment]
I've used this library with one of my own I2C LCD displays and haven't had this problem. The issue is almost certainly with another part of your sketch. If you have reason to believe otherwise, please let me know.

**Comment by p1ngb4ck** [comment]
Sry to bother, but I think you forgot about the different types of displays here.
I have a 1602LCD myself used with I2C header board via I2C connection.
As soon as I use the line
"if(serialLine.available())" (where serialLine is myTransfer), my LCD goes completely blank. No idea why. There must be some side-effects on I2C, even though I didnt uncomment any I2C-header/functions of your lib
