### ISSUE TITLE
Variable

### ISSUE THREAD

**Issue by Neu59** [PowerBroker2/SerialTransfer#79]
Hello friends thanks for this great tool.

I am using this code from the example.

```C++
#include "SerialTransfer.h"


SerialTransfer myTransfer;

struct STRUCT {
  char z;
  float y;
} testStruct;


void setup()
{
  Serial.begin(115200);
  Serial1.begin(115200);
  myTransfer.begin(Serial1);
}


void loop()
{
  if(myTransfer.available())
  {
    myTransfer.rxObj(testStruct);
    Serial.print(testStruct.z);
    Serial.println(testStruct.y);
  }
}
```
My level of programming is very basic. I am trying to extract the variable float to use it in other functions of my code and I don't know how to do it.
Can you help me, thank you.

**Comment by PowerBroker2** [comment]
For questions like this, please use the [Arduino Forum](https://forum.arduino.cc/)

**Comment by Neu59** [comment]
Thanks friend, sorry if it was an inappropriate question

**Comment by PowerBroker2** [comment]
No worries, good luck!

**Comment by Neu59** [comment]
I got it very simple

if(myTransfer.available())
  {
    myTransfer.rxObj(testStruct);
    Serial.print(testStruct.z);
    Serial.println(testStruct.y);
    variable=(testStruct.y);
  }
 float variable;    :+1:
