### ISSUE TITLE
Transmitter using `.sendDatum(char[])`, receiver getting garbage

### ISSUE THREAD

**Issue by MaffooClock** [PowerBroker2/SerialTransfer#80]
**Describe the bug**
I'm not certain that there's a bug in this library, but I thought I'd share this just in case.  At the very least, maybe someone will spot something else wrong.

My implementation is intended to facilitate the transfer of very short plain text strings, but also ArduinoJson data, which is serialized into plain text when transmitted and deserialized when received. 

Previously, I was using the `Serial` objects directly.  This worked for the most part, but on some occasions, the receiving MCUs would appear to get garbage data.  In the case of plain text, it would be random characters like `����` and `␁`.  In the case of ArduinoJson, that library would complain of incomplete or invalid JSON.

I figured my direct use of `Serial` just wasn't perfect enough, so I switched to this library.  It was very easy to refactor my existing code to use it, and even simplified things.  However, immediately the receiver is getting garbage (both ways).  And because of the use of delimiters and CRC-8 and other overhead, the received data is completely goofed (compared to only slightly mangled in my original `Serial` implementation).

It seems like it's a hardware problem, not one with the library, but my hardware implementation is so stinking simple and straightforward (see screenshot), it doesn't make sense that it'd be the problem.

**To Reproduce**
It's not feasible to copy my exact code here, as it's quite long and there's a lot more going on than just serial communications.  Below is a stripped-down, functional equivalent of my implementation.

Trasmitter:
```C++
#include <Arduino.h>
#include <SerialTransfer.h>

SerialTransfer MCUlink;

void setup()
{
  SerialMCU.begin( 115200 );
  MCUlink.begin( SerialMCU );
}

void loop()
{
  const char message[] = "PING";
  MCUlink.sendDatum( message );

  while( true );
}
```

Receiver:
```C++
#include <Arduino.h>
#include <SerialTransfer.h>

SerialTransfer MCUlink;

void checkSerialInput()
{
  if( !MCUlink.available() )
    return;
  
  char messageBuffer[8];
  bool messageReceived = false;
  
  uint32_t timeout = millis() + 10000;
  while( !messageReceived && MCUlink.available() )
  {
    if( millis() > timeout )
    {
        SerialUSB.println(F( "Failed to read entire message from sender." ));
        return;
    }

    delay( 100 );

    if( MCUlink.rxObj( messageBuffer ) > 0 )
      messageReceived = true;
  }

  messageBuffer[strlen(messageBuffer)] = '\0';
  
  SerialUSB.println( messageBuffer );
}

void setup()
{
  SerialMCU.begin( 115200 );
  MCUlink.begin( SerialMCU );
}

void loop()
{
  checkSerialInput();
}
```

**Expected behavior**
I expect to send a plain text string (`char[]` or `char*`) from the transmitting MCU and receive exactly the same string on the receiving MCU.  Instead, the receiver believes it has received strings like `����` and `␁`

**Screenshots**
The two highlighted tracks are the hardware UART lines -- direct connections between the TX and RX pins of each MCU:
<img width="1592" alt="Screen Shot 2022-01-04 at 08 50 43" src="https://user-images.githubusercontent.com/540782/148077318-ab45d2c8-5b0a-4fc6-8491-87fb63faed1c.png">

**Desktop (please complete the following information):**
N/A

**Smartphone (please complete the following information):**
N/A

**Additional context**
These MCUs are mounted together on a custom carrier board, which has the TX and RX pins of the hardware UARTs connected directly between each MCU.  The MCUs are a [MicroMod Teensy](https://www.sparkfun.com/products/16402) (basically a Teensy 4.x), and a [MicroMod RP2040](https://www.sparkfun.com/products/17720).  The Teensy sends a small textual command to the RP2040, and the RP2040 responds with JSON data.

I've tried different baud rates, exact same behavior.  I also thought I'd try SoftwareSerial, but apparently that won't compile for an RP2040.

**Comment by PowerBroker2** [comment]
If you take a look at the `sendDatum()` function, you can see that the library assumes the length of the datum to be sent via `sizeof()` unless the user specifies a custom size:

https://github.com/PowerBroker2/SerialTransfer/blob/932c426dc134cd6cdf428108b2a2d4a819acae65/src/SerialTransfer.h#L75-L96

The reason I bring this up is because if you pass a char array pointer to `sendDatum()` with no secondary argument, the library will assume you mean to send 2 bytes since char pointers are 2 bytes long on most Arduinos.

Assuming correct wiring, matching bauds, etc, the fix for the above issue is to do the following:

```C++
const char message[] = "PING";
MCUlink.sendDatum( message, strlen(message) + 1 ); // + 1 to retain terminating char
```

**Comment by MaffooClock** [comment]
Thank you for the reply.

I have looked through the library source, and it looked to me that the second argument for `sendDatum()` had a default of `sizeof(T)`, so I assumed I didn't need it (but there's a mistake in my logic, I just noticed!).

On further thought, if I had a `char[8]` and only send four characters, `sizeof()` would give the wrong length, so your suggestion of `strlen() + 1` would be more appropriate.  And through that, I now see that I misinterpreted the defaults -- I was looking at `T` and not `val`.  Derp.

I'll go stand in the corner for five minutes, then I'll fix my stupidity and try again...

**Comment by PowerBroker2** [comment]
Nah, it's a gotcha that is hard to catch and my documentation honestly isn't the best. Plus, I don't usually expect people to read the source comments so I figured I'd point it out. Btw, it looks like a cool project - what does it do?

**Comment by MaffooClock** [comment]
It's a device that monitors power from a particular type of equipment.

The Teensy is responsible for managing a Cat M1/NB modem and a connection to AWS MQTT service.

The RP2040 has two cores (so a `setup()` + `setup1()` and `loop()` + `loop1()`, which is damn handy!), with one loop responsible for reading the voltage and current sensors and constantly calculating volts, amps, real power (W), apparent power (VA), and power factor; and the other loop listening to the serial port, waiting to receive a command from the Teensy to report it's current calculation data.

At the other end is a web-based platform where all of the data from these mass-deployed devices can be viewed, interpreted, and used to trigger events and other actions.

<img width="1624" alt="Screen Shot 2022-01-04 at 13 30 26" src="https://user-images.githubusercontent.com/540782/148113793-71277fbd-028b-4ca3-81af-6ce8e4e49239.png">
<img width="1393" alt="Screen Shot 2022-01-04 at 13 33 22" src="https://user-images.githubusercontent.com/540782/148113797-6c5d7c31-f03a-4117-918b-89fc00116f7e.png">


But none of this will happen if I don't get the damn serial connection to work!

Since this library can use I2C and SPI, perhaps I can take that for a spin...

**Comment by PowerBroker2** [comment]
Super impressive work!

> Since this library can use I2C and SPI, perhaps I can take that for a spin...

The Serial and I2C portions of the lib are very stable, but the SPI portion isn't as stable. This is because core developers for certain Arduino boards refuse to keep the SPI API the same - making it impossible to guarantee the lib will work for all Arduinos.

**Comment by MaffooClock** [comment]
Welp, neither I2C nor SPI will work (in my case, anyway).

I2C worked, but only one direction; I could send a "command" from the Teensy (slave) to the RP2040 (master), but the RP2040 could not send a response.  It seems that the way I2C is implemented in this library, it's Slave -> Master only.  The [`sendDatum()`](https://github.com/PowerBroker2/SerialTransfer/blob/932c426dc134cd6cdf428108b2a2d4a819acae65/src/I2CTransfer.h#L22) requires an address to send to (which is skipped in [the examples](https://github.com/PowerBroker2/SerialTransfer/blob/932c426dc134cd6cdf428108b2a2d4a819acae65/examples/i2c_tx_datum/i2c_tx_datum.ino#L26), by the way), which indicates to me that Master -> Slave isn't possible (or else I'm not smart enough to see it).

And for SPI, after following the example, the RP2040 doesn't understand `SPCR` nor `SPE` constants (but the Teensy does), and I'm unwilling to spend the time to dig into the [Arduino library for the RP2040](https://github.com/earlephilhower/arduino-pico) to figure it out.

Damn, one brick wall after another!

Anyway, it's pretty clear that there's not a bug with the `SerialTransfer` -- there's something not right about the UART hardware on one of these MicroMod modules, as there can't possibly be anything wrong with the wiring between the two UARTs.  So, we can close this issue.

**Comment by MaffooClock** [comment]
> Super impressive work!

Fanx!

> The Serial and I2C portions of the lib are very stable

I agree; very clean code without any bloat.  Well done!

I was very eager to use it, and if I can figure out what the problem is with the UART link, this will be the perfect solution.  Regardless, I starred it anyway :)

**Comment by MaffooClock** [comment]
For what it's worth...

As previously confirmed, the problem I'm having is not caused by a bug in this library (there's isn't one).  Just continuing to document my experience purely for (my own) posterity.

I wrote a whole new pair of programs for the Teensy and RP2040 -- the ONLY thing they do is utilize this library to send and receive PING and PONG messages.  The Teensy sends a PING to the RP2040, the RP2040 acknowledges receipt of that string and sends back a PONG, and finally the Teensy acknowledges receipt of the PONG, with each of these steps printing said action to the console.

At first, it didn't work, but I soon figured out why.  There was a way that I was using the `available()` and `rxObj()` methods, which was previously how I was handling incoming raw `Serial` data to detect if I'd received complete data.

 👎🏻👎🏻👎🏻
```
  MCUlink.sendDatum( COMMAND_SEND_READ, strlen( COMMAND_SEND_READ ) + 1 );
  delay( 100 );

  char messageBuffer[256];
  bool messageReceived = false;

  uint32_t timeout = millis() + 10000;
  while( !messageReceived && MCUlink.available() )
  {
    if( millis() > timeout )
    {
      SerialUSB.println(F( "Failed to request data from RP2040." ));
      SerialUSB.println();

      return;
    }

    delay( 100 );

    if( MCUlink.rxObj( messageBuffer ) > 0 )
      messageReceived = true;
  }

  messageBuffer[strlen(messageBuffer)] = '\0';
```

The drop-in replacement of this library didn't work with that (and actually wasn't necessary!), and wiping all that out and using just a single line for `rxObj()` fixed that.

👍🏻👍🏻👍🏻
```
  MCUlink.sendDatum( COMMAND_SEND_READ, strlen( COMMAND_SEND_READ ) + 1 );
  delay( 100 );

  char messageBuffer[256];

  // Here's where all the unnecessary crap was... bye, Felicia!

  MCUlink.rxObj( messageBuffer );
  messageBuffer[strlen(messageBuffer)] = '\0';
```

Finally, I had both controllers sending/receiving text over serial!  🥳  Time to make those same adjustments to the real programs...

The real program in the RP2040 worked right off after making those changes.  It was receiving various requests from the real program in the Teensy and responding with data as expected.  Perfect.

However, the Teensy now shows that every response it gets from the RP2040 is empty, even though the RP2040 is receiving everything sent to it from the Teensy.  I've checked at least 976 times that what worked in the test program for the Teensy is exactly what's in the real program (which also matches what's in the real program for the RP2040) -- I'm certain I'm not missing anything (but obviously I must be, or it'd be working).

At first, I was concerned that sending 256 bytes might be too much in one go (although, that buffer only had around ~70 bytes).  But then I remembered that sending even the shortest string from the RP2040 to the Teensy had the same result (empty).

Ugh.

**Comment by PowerBroker2** [comment]
I haven't analyzed the code too closely, but perhaps this might help:

```C++
MCUlink.rxObj( messageBuffer,  MCUlink.bytesRead );
```

**Comment by MaffooClock** [comment]
AHA!

It occurred to me that the Teensy is executing `rxObj()` almost immediately after `sendDatum()`, and perhaps it should wait for the RP2040 to respond after sending the command rather than assume the response is already available in the serial buffer.

Adding this between the `sendDatum()` and `rxObj()` granted this necessary wait period:
```
  uint32_t timeout = millis() + 1000;
  while( !MCUlink.available() && millis() < timeout )
    yield();
```

When the system is first starting up, the Teensy sends a PING to the RP2040 and expects to receive exactly a PONG, which is to confirm that the other controller is up and the link is established.  Finally, that worked.

There's a second communication action that happens repeatedly, where the Teensy asks the RP2040 to send it whatever data it has collected.  Now, we're getting a `ERROR: STALE PACKET`.  Well, I noticed the `MAX_PACKET_SIZE` constant in Packet.h set to 254, which is short of the 256-byte JSON buffer I'm using.  I reduced the size of my JSON buffer, and also tweaked the `DEFAULT_TIMEOUT` constant.  However, the `STALE PACKET` error persists.

But again, the JSON buffer actually only gets about 70-something bytes (the large size is just to make sure there's plenty of room for any unusually large values, which should be rare).  So I'm guessing the tweaks I made in Packet.h have no bearing.

On the right track, just gotta figure out which side is causing the problem (`sendDatum()` on the trasmitter or `rxObj()` on the receiver).

**Comment by PowerBroker2** [comment]
I don't have a lot of time to look into this until _perhaps_ this weekend, but I'm 100% sure what you are trying to accomplish is possible without editing any of the source files. You might want to check out these two example sketches that transfer a large (**over** 254 byte) text file over serial using the library. Perhaps it might clear up some things:

[TX File](https://github.com/PowerBroker2/SerialTransfer/blob/master/examples/uart_tx_file/uart_tx_file.ino)
[RX File](https://github.com/PowerBroker2/SerialTransfer/blob/master/examples/uart_rx_file/uart_rx_file.ino)

**Comment by MaffooClock** [comment]
> I don't have a lot of time to look into this until _perhaps_ this weekend

Oh, don't trouble yourself too much, man!  After I realized that there wasn't a bug in the library (and so closed the issue), I certainly didn't expect you to do anything.  But I sure appreciate you staying engaged if for nothing else than the conversation!


> I'm 100% sure what you are trying to accomplish is possible without editing any of the source files

I've kinda come to the same conclusion.


> You might want to check out these two example sketches that transfer a large (**over** 254 byte) text file over serial using the library

I hadn't thought of that; good suggestion. 👍🏻

**Comment by MaffooClock** [comment]
Derp.

New day, fresh cup o' Joe, and lookie what I found:
```c++
  MCUlink.sendDatum( COMMAND_SEND_READ, strlen( COMMAND_SEND_READ ) + 1 );
  delay( 100 );  // <-- WTF did I do this for?
  
  uint32_t timeout = millis() + 1000;
  while( !MCUlink.available() && millis() < timeout )
    yield();

  char messageBuffer[128];

  MCUlink.rxObj( messageBuffer );
  messageBuffer[strlen(messageBuffer)] = '\0';
```

That might be just enough time for a packet to be considered stale.  Sheesh.  Took that delay out, and everything works just fine!

I appreciate you sticking with me through my own problem, even though you didn't have to.  Thank you.
