### ISSUE TITLE
Does it work with ESP8266(NODEMCU V3)?

### ISSUE THREAD

**Issue by Senior97** [PowerBroker2/SerialTransfer#92]
I tried examples code named uart_rx_data and uart_tx_data with NodeMCU v3 to NodeMCU v3 but it didnt work. Does it work with NodeMCU ?

Library version : 3.1.2

Regards

**Comment by wassx** [comment]
I currently try to make it run on a NodeMCU 8266 12F but I run into the issue that `Wire.h` is not found. (https://github.com/PowerBroker2/SerialTransfer/blob/c596233371af2735c1a20be8f70f5e5ce30bb278/src/I2CTransfer.h#L4)
@PowerBroker2 any ideas or hints please, what do I need to install here, please?

**Comment by PowerBroker2** [comment]
If the MCU you're using doesn't have the wire library in it's core, you should probably poke around the forums (either Arduino or Espressif). If it continues to be an issue, you could probably comment out all of the files/includes that are associated with Wire.h

**Comment by wassx** [comment]
Ok, I assume the answer is in here: https://www.arduino.cc/reference/en/language/functions/communication/wire/
NodeMCU is not supported with the `Wire.h` library

**Comment by wassx** [comment]
@PowerBroker2 ok thanks for the quick reply, I will use UART for comms and comment the I2C out then.

**Comment by PowerBroker2** [comment]
No prob. I like having I2C and SPI capabilities built into this library, but it's annoying when several board core libraries have inconsistent I2C/SPI APIs causing unnecessary problems with this lib. I probably should at some point put in preprocessor directives to automatically exclude the I2C portion of the lib if compiling for NodeMCU, but I'm busy atm
